### ISSUE TITLE
Whole project?

### ISSUE THREAD

**Issue by cookins** [wildcard1719/RCWSv2#1]
Hey there. I like your projects on YouTube, but you saying that you will share it and, still, there only this one ino file. I know, it's possible impudent from my side, but you can say that you not willing to share your work to public.. that absolutely normal.
There quite many turrets projects you made and it looks like very good job, really. Maybe you can answer, if you will share your projects with us? Like stl files, parts and some diy? Thanks.

**Comment by wildcard1719** [comment]
Hi, first of all, thank you for your interest in my project. I want to share my project. However, once I had stable design skills enough to share projects, I realized that it would take quite a bit of time. I've been busy with studies and competitions for a long time, so I can't guarantee, but I think I'll probably be able to upload a turret tutorial within this year.

**Comment by cookins** [comment]
That great news.
Good luck with studies!
